### PR TITLE
Update SOMpp to latest SOM core library

### PR DESCRIPTION
**Pull request by smarr**
This isn't a classic pull request, more a note about latest updates.

I fixed a couple of issues in SOMpp and updated it to work with the latest version of the SOM core lib that is also used by TruffleSOM.

This brings also support for all [Are We Fast Yet benchmarks](https://github.com/smarr/are-we-fast-yet).

Hope this will give a good foundation to check how well the OMR JIT compiler is doing :)

### CODE REVIEW

**Comment by charliegracie** [comment]
@smarr  this is great and very much appreciated. It will be nice to be on the same playing field as the other implementations.  I was looking at just pushing the changes directly as to avoid the merge commit.  If I make pull requests against the actual SOMpp project would it be better if I just push the changes directly to master or get them via the Pull Request? I am happy either way and just do not want to pollute your history in the event I make Pull Requests

**Comment by smarr** [comment]
If you just fetch the changes and push them, this PR will be closed automatically, I think.

**Comment by charliegracie** [comment]
Cool learn something new everyday about GitHub :)

**Comment by smarr** [comment]
ah, and I looked a little through some of the OMR-related changes here, if you got any refactorings that might be generally useful, I could integrate them to reduce a little the diff. Might help later on.

**Comment by charliegracie** [comment]
Cool that would be useful :)

**Pull request merged**
